---
title: TestCacheInvalidation 중에 웹 계층 파이프라인 실행이 실패했습니다.
description: 설명
solution: Experience Manager as a Cloud Service
product: Experience Manager as a Cloud Service
applies-to: Experience Manager as a Cloud Service
keywords: KCS
resolution: Resolution
internal-notes: answer found in https://dmasupport.slack.com/archives/C013SBSHPKK/p1645102872540889?thread_ts=1645102277.855389&cid=C013SBSHPKK
bug: false
article-created-by: Vincent Frey
article-created-date: 3/31/2022 6:42:09 AM
article-published-by: Vincent Frey
article-published-date: 3/31/2022 6:52:55 AM
version-number: 1
article-number: KA-19052
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=4a8a30af-bdb0-ec11-9840-0022480bde18
exl-id: 29d6e807-7757-443e-9fdf-57af339f00d7
source-git-commit: 6a23faae10364181be7dedc2f408f2ad8d8be3c9
workflow-type: tm+mt
source-wordcount: '114'
ht-degree: 3%

---

# TestCacheInvalidation 중에 웹 계층 파이프라인 실행이 실패했습니다.

## 설명


웹 계층 파이프라인 실행이 실패하고 로그에서 아래 메시지를 관찰할 수 있습니다.

```
=== RUN TestCacheInvalidation
main_test.go:237: Test fails. Expected header 'X-Vhost' to be existing and not: 'catch-all', got: 'catch-all'
--- FAIL: TestCacheInvalidation (0.00s)
FAIL
exit status 1<br><br>
```


## 해상도


다음 [!DNL Dispatcher] 구성에 대한 일부 vhost가 올바르게 구성되어 있습니다. [!DNL Dispatcher] 캐시 무효화(호스트 127.0.0.1에 대해 수행되는 호출) 및 비어 있지 않은 X-Vhost 헤더 세트가 있는 경우

예: https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost#L24

및 X-Vhost 헤더가 https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf#L136에서와 같이 &quot;catch-all&quot;으로 설정된 catch-all vhost에 이 요청되지 않습니다.
