---
title: TestCacheInvalidation 중에 웹 계층 파이프라인 실행이 실패했습니다.
description: 설명
solution: Experience Manager as a Cloud Service
product: Experience Manager as a Cloud Service
applies-to: Experience Manager as a Cloud Service
keywords: KCS
resolution: Resolution
internal-notes: answer found in https://dmasupport.slack.com/archives/C013SBSHPKK/p1645102872540889?thread_ts=1645102277.855389&cid=C013SBSHPKK
bug: false
article-created-by: Vincent Frey
article-created-date: 3/31/2022 6:42:09 AM
article-published-by: Vincent Frey
article-published-date: 3/31/2022 6:52:55 AM
version-number: 1
article-number: KA-19052
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=4a8a30af-bdb0-ec11-9840-0022480bde18
exl-id: 29d6e807-7757-443e-9fdf-57af339f00d7
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '139'
ht-degree: 2%

---

# TestCacheInvalidation 중에 웹 계층 파이프라인 실행이 실패했습니다.

## 설명


웹 계층 파이프라인 실행이 실패하고 로그에서 아래 메시지를 관찰할 수 있습니다.
<br><br>=== TestCacheInvalidation 실행
<br>main_test.go:237: 테스트에 실패했습니다. &#39;X-Vhost&#39; 헤더가 있어야 하는데 다음이 아닙니다. &#39;catch-all&#39;, &#39;catch-all&#39;
<br>— 실패: TestCacheInvalidation(0.00s)
<br>실패
<br>종료 상태 1<br><br>



## 해상도


디스패처 구성이 디스패처 캐시 무효화에 대한 일부 호스트를 올바르게 구성했는지(127.0.0.1을 호스팅하기 위해 수행되는 호출) 및 https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost#L24에서와 같이 비어 있지 않은 X-Vhost 헤더 세트가 있고 요청이 https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf#L136에서 &quot;catch-all&quot;로 설정된 X-Vhost 헤더가 있는 catch-all 호스트에 도달하지 않는지 확인합니다.
